### ISSUE TITLE
Update returning 204 

### ISSUE THREAD

**Issue by neerajkaushik95** [feathersjs-ecosystem/feathers-rest#127]
I am trying trying to update a document using put and it is returning 204 instead of 404 , when id in the url is wrong.

**Comment by daffl** [comment]
This is probably an issue with the database adapter. Which one are you using and could you share a reproducible example?

**Comment by neerajincaendo** [comment]
I am Using mongoose , 
![screenshot from 2017-08-01 13 00 11](https://user-images.githubusercontent.com/30596393/28814040-8d32e1ae-76b9-11e7-94a0-4e1d05c770d9.png)
