### ISSUE TITLE
Prepare for feathers v3

### ISSUE THREAD

**Issue by kristianmandrup** [feathersjs-ecosystem/feathers-rest#133]
To prepare for [feathers v3](https://github.com/feathersjs/feathers-express/issues/3#issuecomment-333390567), feathers-rest should either be renamed: feathers-rest-express or be moved into feathers core in a separate folder that is exported under the `rest` namespace. The same should be done for other http framework integrations/foundations such as Koa, Hapi etc.

**Comment by daffl** [comment]
The v3 compatible version can be found in https://github.com/feathersjs/feathers-rest/tree/major

I agree that it should be moved eventually but was thinking of leaving it here for now to make the migration less painful and then put in a deprecation warning once there are other frameworks that are support. Thoughts?

**Comment by subodhpareek18** [comment]
Yes I agree to not rename it till we have at least one full framework support, and the whole ecosystem has stabilized. 

Till then not likely to cause any issues, people can just be aware of the fact that default/legacy support is express everything else has an explicit naming.

**Comment by kristianmandrup** [comment]
I got pretty far already. Would love for someone who knows/likes Koa to help me out finishing the feathers REST adapter for Koa. Cheers!

**Comment by kristianmandrup** [comment]
Note that I forked the master branch for my [feathers-rest-koa](https://github.com/kristianmandrup/feathers-rest-koa), but the master is currently very Express centric. I'll look at the `major` branch shortly.

So far I've added a `createSetter` factory method, to provide functions to operate on the `ctx` (in Express on `res`)

```js
function createSetter(ctx) {
  let _ctx = ctx
  return {
    setStatus: (code) => {
      _ctx.code = code
    },
    setHeader: (name, value) => {
      _ctx.set(name, value)
    }
  }
}
```

```js
// ...
else if (method === 'create') {
  setter.setCode(statusCodes.created);
}
```

The main `rest` method now takes options to customise as needed and `use` takes an `async` function

```js
export default function rest(opts = {}) {
  return function () {
    const app = this;

    let jsonOpts = Object.assign({
      limit: '10kb',
      fallback: true
    }, opts);
    let jsonHandler = opts.handler || jsonBody(jsonOpts);

    app.use(jsonHandler);

    app.use(async function (ctx, next) {
      ctx.feathers = {
        provider: 'rest'
      };
      await next();
    });

    app.rest = wrappers;
    let register = opts.register || defaultRegister;
    register(app, opts);
  };
}
```

I would recommend a similar approach in v3 master. Cheers!

**Comment by kristianmandrup** [comment]
Currently the problem is that feathers doesn't seem to add the Koa REST routes via `.use`, as in `test/config.js`:

```js
  app = feathers()
    // Note: rest factory will configure json body parser
    .configure(rest(opts))
    // .use(bodyParser()) // supports json (now done via configure(rest()))

    // FIX: calling .use does not add the routes via koa-router!!
    .use('codes', {
      get(id, params, callback) {
        callback();
      },

      create(data, params, callback) {
        callback(null, data);
      }
    })
    .use('todo', todoService);
```

So how does this currently work and where do I tweak it? 
In `feathers` core?

**Comment by daffl** [comment]
I definitely recommend to go with `feathers@pre` (and what's in the `major` branch) that way you can override `.use` as done in https://github.com/feathersjs/feathers-express/blob/master/lib/index.js#L17. As you pointed out, the setting up of routes is done by pushing a provider to `app.providers` as done in https://github.com/feathersjs/feathers-rest/blob/master/src/index.js#L30. Thanks again for looking into this!

**Comment by daffl** [comment]
I think this can be closed and we track other framework integrations separately. A WIP upgrade guide for v3 can be found at https://gist.github.com/daffl/e718f93acc7bfe32fd1e5aed0f8e7827

**Comment by kristianmandrup** [comment]
Wow! Looks awesome @daffl :) Good job!

**Comment by kristianmandrup** [comment]
With regard to supporting other "frameworks", might be a good idea to start with something simple, such as express with Promise support, then build from there:

https://medium.com/@Abazhenov/using-async-await-in-express-with-node-8-b8af872c0016
https://www.npmjs.com/package/express-promise-router
https://github.com/luin/express-promise

What do you think?
