### ISSUE TITLE
Set Location headers

### ISSUE THREAD

**Issue by niallobrien** [feathersjs-ecosystem/feathers-rest#39]
When creating or updating a resource, a `Location` header with a value of `/<service>/:id` should be set by default. Thanks in advance.

**Comment by daffl** [comment]
I was wondering if it could be implemented as quickly as #21 but the problem is that we somehow need to know what the id property for a service is. I guess we can make an assumption here (e.g. `service._idField` or something) but then have to make sure that all the adapters are updated.

**Comment by ekryski** [comment]
Yeah. Definitely valid but a pretty low priority I think since you get the created object in the response. Unless there is something I am missing we can keep it open but it's going to be a while unless someone outside core wants to tackle it.
